#! /bin/bash

echo "Set environment"

# Custom script to set environment variables like FIJI path TEST path JAVA_HOME
source ~/.bashrc_custom
# Overwrite path to test data
export MOSAIC_PLUGIN_TEST_DATA_PATH=$MOSAIC_PATH/src/test/resources/

mvn clean
mvn package
if [ $? -ne 0 ]
then
        echo "Error during building MosaicSuite package"
        exit 1
fi
