#! /bin/bash

echo "Set environment"

# Custom script to set environment variables like FIJI path TEST path JAVA_HOME
source ~/.bashrc_custom

cd plugin

export ANT_OPTS="-Xms1024m -Xmx4096m -XX:PermSize=1024m -XX:MaxPermSize=2048m"

ant main
if [ $? -ne 0 ]
then
        echo "Error compiling"
        exit 1
fi

ant jtest

if [ $? -ne 0 ]
then
	echo "Error in the unit tests"
	exit 1
fi

cd $FIJI_MOSAIC_PLUGIN_PATH/../..

# During build log4j.properties file is copied to bin directory.
./ImageJ-linux64 -Dlog4j.configuration=file:"$MOSAIC_PLUGIN_PATH/bin/log4j.properties" -- --system -batch test.ijm "username=jenkins"

# check if tmp/test has succeful file

if [ ! -e "/tmp/test/succeful"  ]
then
	echo "Error in the tests"
	exit 1
fi

