#! /bin/bash

echo "Set environment"

# For unkown reason source the file on the slave does not work so we have to do in this horrible way
~/.bashrc

cd plugin

ant main
if [ $? -ne 0 ]
then
        echo "Error compiling"
        exit 1
fi

ant jtest

if [ $? -ne 0 ]
then
	echo "Error in the tests"
	exit 1
fi

cd $FIJI_MOSAIC_PLUGIN_PATH/../..

./ImageJ-linux64 -batch test.ijm "username=incardon"

# check if tmp/test has succeful file

if [ ! -e "/tmp/test/succeful"  ]
then
	echo "Error in the tests"
	exit 1
fi

