#!/bin/bash
FILES=/home/i-bird/Desktop/MOSAIC/image_test_2/ImageJ/plugin/lib/*
for f in $FILES
do
  echo "Processing $f file..."
  # take action on each file. $f store current file name
  jarsigner -verify $f
done


 
#jarsigner -verify commons-beanutils-1.8.3.jar
#jarsigner -verify jcl-over-slf4j-1.6.6.jar
#jarsigner -verify commons-io-2.4.jar
#jarsigner -verify jgrapht-jdk1.6.jar
#jarsigner -verify commons-lang3-3.1.jar
#jarsigner -verify jmatharray.jar
#jarsigner -verify commons-logging-1.1.3.jar
#jarsigner -verify jsch-0.1.49.jar
#jarsigner -verify commons-math3-3.0.jar
#jarsigner -verify jtransforms-2.4.jar
#jarsigner -verify dozer.jar
#jarsigner -verify junit-4.11.jar
#jarsigner -verify edu_mines_jtk.jar
#jarsigner -verify junit-4.8.1.jar
#jarsigner -verify forms-1.3.0.jar
#jarsigner -verify loci_tools.jar
#jarsigner -verify ij-1.49j.jar
#jarsigner -verify miglayout15-swing.jar
#jarsigner -verify ImageJ_3D_Viewer.jar
#jarsigner -verify mpi.jar
#jarsigner -verify imagescience.jar
#jarsigner -verify netcdf-4.2.jar
#jarsigner -verify imglib2-2.0.0-beta-26.jar
#jarsigner -verify rsyntaxtextarea.jar
#jarsigner -verify imglib2-2.0.0-SNAPSHOT.jar
#jarsigner -verify scifio-0.15.1.jar
#jarsigner -verify imglib2-algorithms-2.0.0-beta-26.jar
#jarsigner -verify scifio-0.16.1.jar
#jarsigner -verify imglib2-algorithms-gpl-2.0.0-beta-26.jar
#jarsigner -verify scijava-common-2.22.5.jar
#jarsigner -verify imglib2-algorithms-legacy-2.0.0-beta-26.jar
#jarsigner -verify scijava-common-2.24.0.jar
#jarsigner -verify imglib2-ij-2.0.0-beta-26.jar
#jarsigner -verify slf4j-api-1.7.5.jar
#jarsigner -verify imglib2-meta-2.0.0-beta-26.jar
#jarsigner -verify slf4j-log4j12-1.7.5.jar
#jarsigner -verify imglib2-ops-2.0.0-beta-26.jar
#jarsigner -verify super-csv-2.1.0.jar
#jarsigner -verify imglib2-realtransform-2.0.0-beta-26.jar
#jarsigner -verify super-csv-dozer-2.1.0.jar
#jarsigner -verify imglib2-ui-2.0.0-SNAPSHOT.jar
#jarsigner -verify vecmath.jar
#jarsigner -verify Jama-1.0.2.jar
#jarsigner -verify weka-dev-3.7.6.jar
