zip mosaic_ImageJplugins_docs.zip Bessel_PSF/manual/BesselPSFConvolver_manual.pdf
zip mosaic_ImageJplugins_docs.zip BGS/manual/BGS_manual.pdf
zip mosaic_ImageJplugins_docs.zip ParticleTracker_3D/manual\ addendum/ParticleTracker_manual_addendum.pdf
zip mosaic_ImageJplugins_docs.zip ParticleTracker_3D/sample\ data/kinetochores/Cell1_5frames
zip mosaic_ImageJplugins_docs.zip ParticleTracker_3D/sample\ data/kinetochores/description.txt
zip mosaic_ImageJplugins_docs.zip PoissonNoise/manual/PoissonNoise_manual.pdf
zip mosaic_ImageJplugins_docs.zip PSF_measurement_3D/PSF_measurement_3D.pdf
zip mosaic_ImageJplugins_docs.zip PSF_Tool/sample_image/sample.tif
zip mosaic_ImageJplugins_docs.zip PSF_Tool/Tutorial/PSFtool.pdf
zip mosaic_ImageJplugins_docs.zip Region_Competition/Region_Competition.html
zip mosaic_ImageJplugins_docs.zip Region_Competition/images/*
zip mosaic_ImageJplugins_docs.zip Interaction_Analysis/IAPManual.pdf
zip mosaic_ImageJplugins_docs.zip Seg_Bregman/SplitBregmanSeg.pdf

